image: python:3.12-slim

stages:
  - run

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - apt-get update && apt-get install -y --no-install-recommends build-essential curl git libglib2.0-0 libnss3 libfontconfig1 libxss1 libasound2 libxtst6 libxrandr2 libgtk-3-0 ca-certificates
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt

run_grant_checker:
  stage: run
  script:
    - python grants_monitor.py
  only:
    - schedules
